import React, { useState } from 'react';
import {
  Box,
  Container,
  Typography,
  TextField,
  Button,
  Paper,
  Alert,
  CircularProgress,
  Link as MuiLink,
} from '@mui/material';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Mail, ArrowLeft, CheckCircle, Lock } from 'lucide-react';
import { sendEmail } from '../services/emailService';

const ForgotPassword: React.FC = () => {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const [error, setError] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError('');

    try {
      // Validate email format
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        setError('Please enter a valid email address');
        setIsSubmitting(false);
        return;
      }

      // Generate a random reset token (in production, this would be generated by backend)
      const resetToken = Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
      const resetLink = `${window.location.origin}/reset-password?token=${resetToken}&email=${encodeURIComponent(email)}`;

      // Send password reset email
      await sendEmail({
        to: email,
        subject: 'UnitEd - Password Reset Request',
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
              .container { max-width: 600px; margin: 0 auto; padding: 20px; }
              .header { background: linear-gradient(135deg, #6C47FF 0%, #5A3AD6 100%); color: white; padding: 40px; text-align: center; border-radius: 10px 10px 0 0; }
              .content { background: #f9fafb; padding: 40px; }
              .button { display: inline-block; padding: 14px 32px; background: linear-gradient(135deg, #6C47FF 0%, #5A3AD6 100%); color: white; text-decoration: none; border-radius: 8px; margin: 20px 0; font-weight: 600; }
              .footer { background: #f3f4f6; padding: 20px; text-align: center; font-size: 12px; color: #6b7280; border-radius: 0 0 10px 10px; }
              .warning-box { background: #FEF3C7; border-left: 4px solid #F59E0B; padding: 15px; margin: 20px 0; border-radius: 4px; }
              .info-box { background: #EEF2FF; border-left: 4px solid #6C47FF; padding: 15px; margin: 20px 0; border-radius: 4px; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <h1>🔐 Password Reset Request</h1>
              </div>
              <div class="content">
                <h2>Hello!</h2>
                <p>We received a request to reset your password for your UnitEd account.</p>
                
                <p>Click the button below to reset your password:</p>
                
                <div style="text-align: center; margin: 30px 0;">
                  <a href="${resetLink}" class="button">Reset My Password</a>
                </div>
                
                <p style="color: #6B7280; font-size: 14px;">Or copy and paste this link in your browser:</p>
                <p style="background: white; padding: 12px; border-radius: 6px; word-break: break-all; font-size: 13px; color: #6C47FF;">
                  ${resetLink}
                </p>
                
                <div class="info-box">
                  <p style="margin: 0; color: #4338CA; font-weight: 600;">⏰ This link will expire in 1 hour</p>
                </div>
                
                <div class="warning-box">
                  <p style="margin: 0; color: #92400E;"><strong>⚠️ Didn't request this?</strong></p>
                  <p style="margin: 5px 0 0 0; color: #92400E; font-size: 14px;">If you didn't request a password reset, please ignore this email or contact support if you have concerns.</p>
                </div>
                
                <p style="margin-top: 30px; color: #6B7280; font-size: 14px;">
                  For security reasons, this link will only work once. If you need to reset your password again, please submit a new request.
                </p>
              </div>
              <div class="footer">
                <p>This is an automated message from UnitEd Platform.</p>
                <p>© 2025 UnitEd - Academic Collaboration Platform</p>
              </div>
            </div>
          </body>
          </html>
        `,
      });

      setSubmitSuccess(true);
      
      // In production, you would also save the reset token to database with expiration
      console.log('Password reset email sent to:', email);
      console.log('Reset token:', resetToken);
      
    } catch (err) {
      console.error('Error sending reset email:', err);
      setError('Failed to send reset email. Please try again or contact support.');
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Box
      sx={{
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
        py: 4,
      }}
    >
      <Container maxWidth="sm">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Paper
            elevation={24}
            sx={{
              p: 4,
              borderRadius: 3,
              position: 'relative',
              overflow: 'hidden',
            }}
          >
            {/* Header Icon */}
            <Box
              sx={{
                display: 'flex',
                justifyContent: 'center',
                mb: 3,
              }}
            >
              <Box
                sx={{
                  p: 2,
                  backgroundColor: '#EEF2FF',
                  borderRadius: '50%',
                  display: 'inline-flex',
                }}
              >
                <Lock size={48} color="#6C47FF" />
              </Box>
            </Box>

            {!submitSuccess ? (
              <>
                {/* Title */}
                <Typography
                  variant="h4"
                  align="center"
                  sx={{
                    fontWeight: 700,
                    color: '#111827',
                    mb: 1,
                  }}
                >
                  Forgot Password?
                </Typography>

                <Typography
                  variant="body2"
                  align="center"
                  sx={{
                    color: '#6B7280',
                    mb: 4,
                  }}
                >
                  No worries! Enter your email address and we'll send you a link to reset your password.
                </Typography>

                {/* Error Alert */}
                {error && (
                  <Alert severity="error" sx={{ mb: 3 }} onClose={() => setError('')}>
                    {error}
                  </Alert>
                )}

                {/* Form */}
                <form onSubmit={handleSubmit}>
                  <TextField
                    fullWidth
                    label="Email Address"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                    variant="outlined"
                    placeholder="your.email@university.edu"
                    InputProps={{
                      startAdornment: (
                        <Mail size={20} color="#6B7280" style={{ marginRight: 8 }} />
                      ),
                    }}
                    sx={{ mb: 3 }}
                  />

                  <Button
                    type="submit"
                    fullWidth
                    variant="contained"
                    size="large"
                    disabled={isSubmitting || !email}
                    sx={{
                      py: 1.5,
                      background: 'linear-gradient(135deg, #6C47FF 0%, #5A3AD6 100%)',
                      textTransform: 'none',
                      fontSize: '1rem',
                      fontWeight: 600,
                      mb: 2,
                      '&:hover': {
                        background: 'linear-gradient(135deg, #5A3AD6 0%, #4A2FB8 100%)',
                      },
                      '&:disabled': {
                        background: '#9CA3AF',
                      },
                    }}
                  >
                    {isSubmitting ? (
                      <>
                        <CircularProgress size={20} color="inherit" sx={{ mr: 1 }} />
                        Sending...
                      </>
                    ) : (
                      'Send Reset Link'
                    )}
                  </Button>

                  {/* Back to Login */}
                  <Button
                    fullWidth
                    variant="text"
                    startIcon={<ArrowLeft size={18} />}
                    onClick={() => navigate('/login')}
                    sx={{
                      textTransform: 'none',
                      color: '#6C47FF',
                      fontWeight: 500,
                      '&:hover': {
                        backgroundColor: '#F5F3FF',
                      },
                    }}
                  >
                    Back to Login
                  </Button>
                </form>
              </>
            ) : (
              <>
                {/* Success State */}
                <Box sx={{ textAlign: 'center' }}>
                  <CheckCircle size={64} color="#10B981" />
                  
                  <Typography
                    variant="h5"
                    sx={{
                      fontWeight: 700,
                      color: '#111827',
                      mt: 3,
                      mb: 2,
                    }}
                  >
                    Check Your Email!
                  </Typography>

                  <Typography
                    variant="body1"
                    sx={{
                      color: '#6B7280',
                      mb: 3,
                    }}
                  >
                    We've sent password reset instructions to:
                  </Typography>

                  <Typography
                    variant="h6"
                    sx={{
                      color: '#6C47FF',
                      fontWeight: 600,
                      mb: 3,
                    }}
                  >
                    {email}
                  </Typography>

                  <Alert severity="info" sx={{ mb: 3, textAlign: 'left' }}>
                    <Typography variant="body2" sx={{ mb: 1 }}>
                      <strong>📧 Didn't receive the email?</strong>
                    </Typography>
                    <Typography variant="caption" component="div">
                      • Check your spam/junk folder
                    </Typography>
                    <Typography variant="caption" component="div">
                      • Make sure you entered the correct email
                    </Typography>
                    <Typography variant="caption" component="div">
                      • The link expires in 1 hour
                    </Typography>
                  </Alert>

                  <Button
                    variant="text"
                    onClick={() => {
                      setSubmitSuccess(false);
                      setEmail('');
                    }}
                    sx={{
                      textTransform: 'none',
                      color: '#6C47FF',
                      fontWeight: 500,
                      mb: 2,
                    }}
                  >
                    Try a different email
                  </Button>

                  <Button
                    fullWidth
                    variant="outlined"
                    startIcon={<ArrowLeft size={18} />}
                    onClick={() => navigate('/login')}
                    sx={{
                      textTransform: 'none',
                      borderColor: '#6C47FF',
                      color: '#6C47FF',
                      fontWeight: 500,
                      '&:hover': {
                        borderColor: '#5A3AD6',
                        backgroundColor: '#F5F3FF',
                      },
                    }}
                  >
                    Back to Login
                  </Button>
                </Box>
              </>
            )}

            {/* Footer */}
            <Box sx={{ mt: 4, pt: 3, borderTop: '1px solid #E5E7EB' }}>
              <Typography variant="caption" align="center" display="block" sx={{ color: '#9CA3AF' }}>
                Need help? Contact{' '}
                <MuiLink href="mailto:radhakrishna02256@gmail.com" sx={{ color: '#6C47FF' }}>
                  support
                </MuiLink>
              </Typography>
            </Box>
          </Paper>
        </motion.div>
      </Container>
    </Box>
  );
};

export default ForgotPassword;
